# Generated by Django 4.2.4 on 2023-08-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property_name',
            new_name='property',
        ),
    ]
