# Generated by Django 4.2.4 on 2023-09-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_rename_property_name_propertyimage_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Ogun', 'Ogun'), ('Edo', 'Edo')], default='Lagos', max_length=100),
        ),
    ]
